spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dahaeSpringstudy@gmail.com
    password: wjdekgo99!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
        # show_sql: true
        format_sql: true


logging.level:
  org.springframework: debug
  org.springframework.web : debug
server:
  port: 9090